// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: maany/genesismint/v1/genesismint.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v8/modules/core/23-commitment/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TrustedRoot struct {
	RevisionNumber uint64 `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	RevisionHeight uint64 `protobuf:"varint,2,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
	Hash           []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *TrustedRoot) Reset()         { *m = TrustedRoot{} }
func (m *TrustedRoot) String() string { return proto.CompactTextString(m) }
func (*TrustedRoot) ProtoMessage()    {}
func (*TrustedRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_a08cfa38e3b6bdc3, []int{0}
}
func (m *TrustedRoot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrustedRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrustedRoot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrustedRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustedRoot.Merge(m, src)
}
func (m *TrustedRoot) XXX_Size() int {
	return m.Size()
}
func (m *TrustedRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustedRoot.DiscardUnknown(m)
}

var xxx_messageInfo_TrustedRoot proto.InternalMessageInfo

func (m *TrustedRoot) GetRevisionNumber() uint64 {
	if m != nil {
		return m.RevisionNumber
	}
	return 0
}

func (m *TrustedRoot) GetRevisionHeight() uint64 {
	if m != nil {
		return m.RevisionHeight
	}
	return 0
}

func (m *TrustedRoot) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// Params: what the consumer expects for provider+denoms
type Params struct {
	ProviderClientId      string       `protobuf:"bytes,1,opt,name=provider_client_id,json=providerClientId,proto3" json:"provider_client_id,omitempty" yaml:"provider_client_id"`
	ProviderChainId       string       `protobuf:"bytes,2,opt,name=provider_chain_id,json=providerChainId,proto3" json:"provider_chain_id,omitempty" yaml:"provider_chain_id"`
	AllowedProviderDenom  string       `protobuf:"bytes,3,opt,name=allowed_provider_denom,json=allowedProviderDenom,proto3" json:"allowed_provider_denom,omitempty" yaml:"allowed_provider_denom"`
	MintDenom             string       `protobuf:"bytes,4,opt,name=mint_denom,json=mintDenom,proto3" json:"mint_denom,omitempty" yaml:"mint_denom"`
	GenesisTrustedRoot    *TrustedRoot `protobuf:"bytes,5,opt,name=genesis_trusted_root,json=genesisTrustedRoot,proto3" json:"genesis_trusted_root,omitempty"`
	UseGenesisTrustedRoot bool         `protobuf:"varint,6,opt,name=use_genesis_trusted_root,json=useGenesisTrustedRoot,proto3" json:"use_genesis_trusted_root,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_a08cfa38e3b6bdc3, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetProviderClientId() string {
	if m != nil {
		return m.ProviderClientId
	}
	return ""
}

func (m *Params) GetProviderChainId() string {
	if m != nil {
		return m.ProviderChainId
	}
	return ""
}

func (m *Params) GetAllowedProviderDenom() string {
	if m != nil {
		return m.AllowedProviderDenom
	}
	return ""
}

func (m *Params) GetMintDenom() string {
	if m != nil {
		return m.MintDenom
	}
	return ""
}

func (m *Params) GetGenesisTrustedRoot() *TrustedRoot {
	if m != nil {
		return m.GenesisTrustedRoot
	}
	return nil
}

func (m *Params) GetUseGenesisTrustedRoot() bool {
	if m != nil {
		return m.UseGenesisTrustedRoot
	}
	return false
}

// A single mint instruction proven against provider state
type MintIntent struct {
	MerkleProof               *types.MerkleProof `protobuf:"bytes,1,opt,name=merkle_proof,json=merkleProof,proto3" json:"merkle_proof,omitempty"`
	ProofHeightRevisionNumber uint64             `protobuf:"varint,2,opt,name=proof_height_revision_number,json=proofHeightRevisionNumber,proto3" json:"proof_height_revision_number,omitempty"`
	ProofHeightRevisionHeight uint64             `protobuf:"varint,3,opt,name=proof_height_revision_height,json=proofHeightRevisionHeight,proto3" json:"proof_height_revision_height,omitempty"`
	// Key path pieces. First element must be the store name (e.g., "x-mintburn"),
	// second element is hex of the KV key bytes (e.g., "0131").
	KeyPath []string `protobuf:"bytes,4,rep,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	// Base64-encoded value (provider KV value for that key)
	Value           string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	ProviderChainId string `protobuf:"bytes,6,opt,name=provider_chain_id,json=providerChainId,proto3" json:"provider_chain_id,omitempty"`
	// Minting details (mirror)
	AmountDenom string `protobuf:"bytes,7,opt,name=amount_denom,json=amountDenom,proto3" json:"amount_denom,omitempty"`
	AmountValue string `protobuf:"bytes,8,opt,name=amount_value,json=amountValue,proto3" json:"amount_value,omitempty"`
	EscrowId    string `protobuf:"bytes,9,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	Recipient   string `protobuf:"bytes,10,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (m *MintIntent) Reset()         { *m = MintIntent{} }
func (m *MintIntent) String() string { return proto.CompactTextString(m) }
func (*MintIntent) ProtoMessage()    {}
func (*MintIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a08cfa38e3b6bdc3, []int{2}
}
func (m *MintIntent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintIntent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintIntent.Merge(m, src)
}
func (m *MintIntent) XXX_Size() int {
	return m.Size()
}
func (m *MintIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_MintIntent.DiscardUnknown(m)
}

var xxx_messageInfo_MintIntent proto.InternalMessageInfo

func (m *MintIntent) GetMerkleProof() *types.MerkleProof {
	if m != nil {
		return m.MerkleProof
	}
	return nil
}

func (m *MintIntent) GetProofHeightRevisionNumber() uint64 {
	if m != nil {
		return m.ProofHeightRevisionNumber
	}
	return 0
}

func (m *MintIntent) GetProofHeightRevisionHeight() uint64 {
	if m != nil {
		return m.ProofHeightRevisionHeight
	}
	return 0
}

func (m *MintIntent) GetKeyPath() []string {
	if m != nil {
		return m.KeyPath
	}
	return nil
}

func (m *MintIntent) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *MintIntent) GetProviderChainId() string {
	if m != nil {
		return m.ProviderChainId
	}
	return ""
}

func (m *MintIntent) GetAmountDenom() string {
	if m != nil {
		return m.AmountDenom
	}
	return ""
}

func (m *MintIntent) GetAmountValue() string {
	if m != nil {
		return m.AmountValue
	}
	return ""
}

func (m *MintIntent) GetEscrowId() string {
	if m != nil {
		return m.EscrowId
	}
	return ""
}

func (m *MintIntent) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

// GenesisState accepts your bundle.json
type GenesisState struct {
	Params           *Params       `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Mints            []*MintIntent `protobuf:"bytes,2,rep,name=mints,proto3" json:"mints,omitempty"`
	ClaimedEscrowIds []string      `protobuf:"bytes,3,rep,name=claimed_escrow_ids,json=claimedEscrowIds,proto3" json:"claimed_escrow_ids,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a08cfa38e3b6bdc3, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisState) GetMints() []*MintIntent {
	if m != nil {
		return m.Mints
	}
	return nil
}

func (m *GenesisState) GetClaimedEscrowIds() []string {
	if m != nil {
		return m.ClaimedEscrowIds
	}
	return nil
}

func init() {
	proto.RegisterType((*TrustedRoot)(nil), "maany.genesismint.v1.TrustedRoot")
	proto.RegisterType((*Params)(nil), "maany.genesismint.v1.Params")
	proto.RegisterType((*MintIntent)(nil), "maany.genesismint.v1.MintIntent")
	proto.RegisterType((*GenesisState)(nil), "maany.genesismint.v1.GenesisState")
}

func init() {
	proto.RegisterFile("maany/genesismint/v1/genesismint.proto", fileDescriptor_a08cfa38e3b6bdc3)
}

var fileDescriptor_a08cfa38e3b6bdc3 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x4f, 0x4e, 0xdb, 0x40,
	0x14, 0xc6, 0x31, 0x09, 0x21, 0x9e, 0x44, 0x05, 0x46, 0xa1, 0x72, 0x68, 0x48, 0x82, 0x2b, 0x95,
	0xa8, 0x6a, 0x6d, 0x41, 0xa1, 0x95, 0xba, 0xa9, 0x44, 0xff, 0x11, 0x55, 0xb4, 0xd1, 0x50, 0xb5,
	0x52, 0x37, 0x96, 0x63, 0x0f, 0xf1, 0x08, 0xdb, 0x13, 0xd9, 0xe3, 0x40, 0x7a, 0x8a, 0x9e, 0xa3,
	0xeb, 0x2e, 0x7b, 0x80, 0x2e, 0x59, 0x76, 0x15, 0x55, 0x70, 0x83, 0x9c, 0xa0, 0xf2, 0xcc, 0x10,
	0x27, 0x10, 0x76, 0x7e, 0xdf, 0xfb, 0xf9, 0x7b, 0xf2, 0xbc, 0x6f, 0x0c, 0x1e, 0x05, 0xb6, 0x1d,
	0x0e, 0xcd, 0x1e, 0x0e, 0x71, 0x4c, 0xe2, 0x80, 0x84, 0xcc, 0x1c, 0xec, 0x4c, 0x97, 0x46, 0x3f,
	0xa2, 0x8c, 0xc2, 0x0a, 0xe7, 0x8c, 0xe9, 0xc6, 0x60, 0x67, 0xa3, 0xd2, 0xa3, 0x3d, 0xca, 0x01,
	0x33, 0x7d, 0x12, 0xec, 0xc6, 0x36, 0xe9, 0x3a, 0xa6, 0x43, 0x23, 0x6c, 0x3a, 0x34, 0x08, 0x08,
	0x0b, 0xb0, 0x70, 0xcd, 0x2a, 0x09, 0x56, 0x7b, 0x94, 0xf6, 0x7c, 0x6c, 0xf2, 0xaa, 0x9b, 0x9c,
	0x98, 0xe9, 0x08, 0x5e, 0xe8, 0x31, 0x28, 0x7d, 0x8e, 0x92, 0x98, 0x61, 0x17, 0x51, 0xca, 0xe0,
	0x36, 0x58, 0x89, 0xf0, 0x80, 0xc4, 0x84, 0x86, 0x56, 0x98, 0x04, 0x5d, 0x1c, 0x69, 0x4a, 0x53,
	0x69, 0xe5, 0xd1, 0xbd, 0x6b, 0xf9, 0x23, 0x57, 0x67, 0x40, 0x0f, 0x93, 0x9e, 0xc7, 0xb4, 0xc5,
	0x59, 0xf0, 0x90, 0xab, 0x10, 0x82, 0xbc, 0x67, 0xc7, 0x9e, 0x96, 0x6b, 0x2a, 0xad, 0x32, 0xe2,
	0xcf, 0xfa, 0xef, 0x1c, 0x28, 0x74, 0xec, 0xc8, 0x0e, 0x62, 0xf8, 0x01, 0xc0, 0x7e, 0x44, 0x07,
	0xc4, 0xc5, 0x91, 0xe5, 0xf8, 0x04, 0x87, 0xcc, 0x22, 0x2e, 0x9f, 0xa9, 0x1e, 0x6c, 0x8e, 0x47,
	0x8d, 0xea, 0xd0, 0x0e, 0xfc, 0x97, 0xfa, 0x6d, 0x46, 0x47, 0xab, 0xd7, 0xe2, 0x6b, 0xae, 0xb5,
	0x5d, 0x78, 0x08, 0xd6, 0x32, 0xd0, 0xb3, 0x49, 0x98, 0x7a, 0x2d, 0x72, 0xaf, 0xda, 0x78, 0xd4,
	0xd0, 0x6e, 0x7a, 0x49, 0x44, 0x47, 0x2b, 0x13, 0xab, 0x54, 0x6a, 0xbb, 0xf0, 0x2b, 0xb8, 0x6f,
	0xfb, 0x3e, 0x3d, 0xc3, 0xae, 0x35, 0xc1, 0x5d, 0x1c, 0xd2, 0x80, 0x7f, 0x87, 0x7a, 0xb0, 0x35,
	0x1e, 0x35, 0x36, 0x85, 0xdd, 0x7c, 0x4e, 0x47, 0x15, 0xd9, 0xe8, 0x48, 0xfd, 0x4d, 0x2a, 0xc3,
	0x3d, 0x00, 0xd2, 0xa5, 0x4a, 0xb3, 0x3c, 0x37, 0x5b, 0x1f, 0x8f, 0x1a, 0x6b, 0xc2, 0x2c, 0xeb,
	0xe9, 0x48, 0x4d, 0x0b, 0xf1, 0xd6, 0x31, 0xa8, 0xc8, 0x44, 0x58, 0x4c, 0x6c, 0xcb, 0x8a, 0x28,
	0x65, 0xda, 0x52, 0x53, 0x69, 0x95, 0x76, 0xb7, 0x8c, 0x79, 0xa1, 0x31, 0xa6, 0xf6, 0x8a, 0xa0,
	0xec, 0x4d, 0xef, 0xfa, 0x05, 0xd0, 0x92, 0x18, 0x5b, 0x73, 0x8d, 0x0b, 0x4d, 0xa5, 0x55, 0x44,
	0xeb, 0x49, 0x8c, 0xdf, 0xdf, 0x7a, 0x51, 0xff, 0x95, 0x03, 0xe0, 0x88, 0x84, 0xac, 0x1d, 0x32,
	0x1c, 0x32, 0xf8, 0x0e, 0x94, 0x03, 0x1c, 0x9d, 0xfa, 0x38, 0x3d, 0x02, 0x7a, 0xc2, 0x97, 0x57,
	0xda, 0x7d, 0x68, 0x90, 0xae, 0x63, 0xa4, 0xe9, 0x34, 0xa6, 0xf2, 0x38, 0xd8, 0x31, 0x8e, 0x38,
	0xdb, 0x49, 0x51, 0x54, 0x0a, 0xb2, 0x02, 0xbe, 0x02, 0x35, 0x6e, 0x20, 0xf3, 0x64, 0xdd, 0x0c,
	0xa2, 0xc8, 0x57, 0x95, 0x33, 0x22, 0x5c, 0x68, 0x36, 0x93, 0x77, 0x1a, 0xc8, 0x80, 0xe6, 0xee,
	0x34, 0x90, 0x59, 0xad, 0x82, 0xe2, 0x29, 0x1e, 0x5a, 0x7d, 0x9b, 0x79, 0x5a, 0xbe, 0x99, 0x6b,
	0xa9, 0x68, 0xf9, 0x14, 0x0f, 0x3b, 0x36, 0xf3, 0x60, 0x05, 0x2c, 0x0d, 0x6c, 0x3f, 0xc1, 0xfc,
	0xc8, 0x55, 0x24, 0x0a, 0xf8, 0x78, 0x5e, 0xe0, 0x0a, 0x9c, 0xb8, 0x15, 0xa9, 0x2d, 0x50, 0xb6,
	0x03, 0x9a, 0x4c, 0x76, 0xbf, 0xcc, 0xb1, 0x92, 0xd0, 0xc4, 0x9a, 0x33, 0x44, 0xcc, 0x2a, 0x4e,
	0x23, 0x5f, 0xf8, 0xc4, 0x07, 0x40, 0xc5, 0xb1, 0x13, 0xd1, 0xb3, 0x74, 0x92, 0xca, 0xfb, 0x45,
	0x21, 0xb4, 0x5d, 0x58, 0x03, 0x6a, 0x84, 0x1d, 0xd2, 0x4f, 0xaf, 0x83, 0x06, 0x78, 0x33, 0x13,
	0xf4, 0x9f, 0x0a, 0x28, 0xcb, 0x6d, 0x1e, 0x33, 0x9b, 0x61, 0xb8, 0x07, 0x0a, 0x7d, 0x7e, 0x0b,
	0xe5, 0xca, 0x6a, 0xf3, 0x73, 0x24, 0x6e, 0x2a, 0x92, 0x2c, 0x7c, 0x0e, 0x96, 0xd2, 0x4e, 0xac,
	0x2d, 0x36, 0x73, 0xad, 0xd2, 0x6e, 0x73, 0xfe, 0x4b, 0x59, 0x3e, 0x90, 0xc0, 0xe1, 0x13, 0x00,
	0x1d, 0xdf, 0x26, 0x01, 0x76, 0xad, 0xc9, 0x17, 0xc4, 0x5a, 0x8e, 0x1f, 0xf3, 0xaa, 0xec, 0xbc,
	0x95, 0x5f, 0x12, 0x1f, 0x7c, 0xfa, 0x73, 0x59, 0x57, 0x2e, 0x2e, 0xeb, 0xca, 0xbf, 0xcb, 0xba,
	0xf2, 0xe3, 0xaa, 0xbe, 0x70, 0x71, 0x55, 0x5f, 0xf8, 0x7b, 0x55, 0x5f, 0xf8, 0xb6, 0xdf, 0x23,
	0xcc, 0x4b, 0xba, 0x69, 0xaa, 0x4c, 0x3e, 0xfa, 0xe9, 0xf9, 0xf0, 0xbb, 0x7c, 0x72, 0xf1, 0xb9,
	0x39, 0xd8, 0x37, 0xcf, 0x67, 0xfe, 0xb3, 0x6c, 0xd8, 0xc7, 0x71, 0xb7, 0xc0, 0xff, 0x77, 0xcf,
	0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x37, 0x83, 0x38, 0x5c, 0x89, 0x05, 0x00, 0x00,
}

func (m *TrustedRoot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrustedRoot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrustedRoot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.RevisionHeight != 0 {
		i = encodeVarintGenesismint(dAtA, i, uint64(m.RevisionHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.RevisionNumber != 0 {
		i = encodeVarintGenesismint(dAtA, i, uint64(m.RevisionNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UseGenesisTrustedRoot {
		i--
		if m.UseGenesisTrustedRoot {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.GenesisTrustedRoot != nil {
		{
			size, err := m.GenesisTrustedRoot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesismint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MintDenom) > 0 {
		i -= len(m.MintDenom)
		copy(dAtA[i:], m.MintDenom)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.MintDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AllowedProviderDenom) > 0 {
		i -= len(m.AllowedProviderDenom)
		copy(dAtA[i:], m.AllowedProviderDenom)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.AllowedProviderDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ProviderChainId) > 0 {
		i -= len(m.ProviderChainId)
		copy(dAtA[i:], m.ProviderChainId)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.ProviderChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ProviderClientId) > 0 {
		i -= len(m.ProviderClientId)
		copy(dAtA[i:], m.ProviderClientId)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.ProviderClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MintIntent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintIntent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintIntent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.EscrowId) > 0 {
		i -= len(m.EscrowId)
		copy(dAtA[i:], m.EscrowId)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.EscrowId)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.AmountValue) > 0 {
		i -= len(m.AmountValue)
		copy(dAtA[i:], m.AmountValue)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.AmountValue)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.AmountDenom) > 0 {
		i -= len(m.AmountDenom)
		copy(dAtA[i:], m.AmountDenom)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.AmountDenom)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ProviderChainId) > 0 {
		i -= len(m.ProviderChainId)
		copy(dAtA[i:], m.ProviderChainId)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.ProviderChainId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintGenesismint(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.KeyPath) > 0 {
		for iNdEx := len(m.KeyPath) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.KeyPath[iNdEx])
			copy(dAtA[i:], m.KeyPath[iNdEx])
			i = encodeVarintGenesismint(dAtA, i, uint64(len(m.KeyPath[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ProofHeightRevisionHeight != 0 {
		i = encodeVarintGenesismint(dAtA, i, uint64(m.ProofHeightRevisionHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.ProofHeightRevisionNumber != 0 {
		i = encodeVarintGenesismint(dAtA, i, uint64(m.ProofHeightRevisionNumber))
		i--
		dAtA[i] = 0x10
	}
	if m.MerkleProof != nil {
		{
			size, err := m.MerkleProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesismint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClaimedEscrowIds) > 0 {
		for iNdEx := len(m.ClaimedEscrowIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ClaimedEscrowIds[iNdEx])
			copy(dAtA[i:], m.ClaimedEscrowIds[iNdEx])
			i = encodeVarintGenesismint(dAtA, i, uint64(len(m.ClaimedEscrowIds[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Mints) > 0 {
		for iNdEx := len(m.Mints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Mints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesismint(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesismint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesismint(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesismint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TrustedRoot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RevisionNumber != 0 {
		n += 1 + sovGenesismint(uint64(m.RevisionNumber))
	}
	if m.RevisionHeight != 0 {
		n += 1 + sovGenesismint(uint64(m.RevisionHeight))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProviderClientId)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	l = len(m.ProviderChainId)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	l = len(m.AllowedProviderDenom)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	l = len(m.MintDenom)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	if m.GenesisTrustedRoot != nil {
		l = m.GenesisTrustedRoot.Size()
		n += 1 + l + sovGenesismint(uint64(l))
	}
	if m.UseGenesisTrustedRoot {
		n += 2
	}
	return n
}

func (m *MintIntent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MerkleProof != nil {
		l = m.MerkleProof.Size()
		n += 1 + l + sovGenesismint(uint64(l))
	}
	if m.ProofHeightRevisionNumber != 0 {
		n += 1 + sovGenesismint(uint64(m.ProofHeightRevisionNumber))
	}
	if m.ProofHeightRevisionHeight != 0 {
		n += 1 + sovGenesismint(uint64(m.ProofHeightRevisionHeight))
	}
	if len(m.KeyPath) > 0 {
		for _, s := range m.KeyPath {
			l = len(s)
			n += 1 + l + sovGenesismint(uint64(l))
		}
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	l = len(m.ProviderChainId)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	l = len(m.AmountDenom)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	l = len(m.AmountValue)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	l = len(m.EscrowId)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovGenesismint(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovGenesismint(uint64(l))
	}
	if len(m.Mints) > 0 {
		for _, e := range m.Mints {
			l = e.Size()
			n += 1 + l + sovGenesismint(uint64(l))
		}
	}
	if len(m.ClaimedEscrowIds) > 0 {
		for _, s := range m.ClaimedEscrowIds {
			l = len(s)
			n += 1 + l + sovGenesismint(uint64(l))
		}
	}
	return n
}

func sovGenesismint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesismint(x uint64) (n int) {
	return sovGenesismint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TrustedRoot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesismint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrustedRoot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrustedRoot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionNumber", wireType)
			}
			m.RevisionNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevisionNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionHeight", wireType)
			}
			m.RevisionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevisionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesismint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesismint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesismint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedProviderDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedProviderDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisTrustedRoot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GenesisTrustedRoot == nil {
				m.GenesisTrustedRoot = &TrustedRoot{}
			}
			if err := m.GenesisTrustedRoot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UseGenesisTrustedRoot", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UseGenesisTrustedRoot = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesismint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesismint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MintIntent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesismint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintIntent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintIntent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MerkleProof == nil {
				m.MerkleProof = &types.MerkleProof{}
			}
			if err := m.MerkleProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHeightRevisionNumber", wireType)
			}
			m.ProofHeightRevisionNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofHeightRevisionNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHeightRevisionHeight", wireType)
			}
			m.ProofHeightRevisionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofHeightRevisionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyPath = append(m.KeyPath, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesismint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesismint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesismint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mints = append(m.Mints, &MintIntent{})
			if err := m.Mints[len(m.Mints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedEscrowIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesismint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesismint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimedEscrowIds = append(m.ClaimedEscrowIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesismint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesismint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesismint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesismint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesismint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesismint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesismint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesismint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesismint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesismint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesismint = fmt.Errorf("proto: unexpected end of group")
)
